export class GridConstants {
  static VERTICAL_RECORD_SHOW_LIMT: number = 10;
  static HORIZONTAL_COLUMN_SHOW_LIMIT: number = 8;
  static DEFAULT_NUMBER_OF_RECORDS_PER_PAGE: number = 10;
  static HORIZONTAL_MAX_ACTION_BUTTON_LIMIT: number = 3;
  static VERTICAL_COLUMN_SHOW_LIMIT_IN_COLUMN_SHOW_HIDE_COMPONENT: number = 15;
  static VERTICAL_FILTER_OPTION_SHOW_LIMIT_IN_LIST_FILTER_COMPONENT: number = 15;
  static LETTER_LENGTH_FOR_LENGTHY_DATA: number = 21;
}
